<?php

/**
 * Controller is the customized base controller class.
 * All controller classes for this application should extend from this base class.
 */
class Controller extends CController
{
    /**
     * @var string the default layout for the controller view. Defaults to '//layouts/column1',
     * meaning using a single column layout. See 'protected/views/layouts/column1.php'.
     */
    public $layout = '//layouts/column1';
    /**
     * @var array context menu items. This property will be assigned to {@link CMenu::items}.
     */
    public $menu = array();
    /**
     * @var array the breadcrumbs of the current page. The value of this property will
     * be assigned to {@link CBreadcrumbs::links}. Please refer to {@link CBreadcrumbs::links}
     * for more details on how to specify this property.
     */
    public $breadcrumbs = array();

    /**
     * Удаляет кеш по id, принудительно, т.к.
     * метод Yii::app()->cache->delete
     * не находит его по id.
     * @param integer or array of integer $id
     * @param array $properties
     */
    public function deleteCache($id, $properties = array())
    {
        if (is_array($id)) {
            foreach ($id as $i) {
                $this->deleteCache($i, $properties);
            }
        } else {
            // see https://github.com/yiisoft/yii/issues/2541
            $properties['id'] = $id;
            $properties['duration'] = 0;
            $properties['varyByRoute'] = false;
            $outputCache = $this->createWidget('COutputCache', $properties);

            //this line should delete the value from the app-cache generated by the COutputCache
            //calls Yii::app()->cache->delete($outputCache->getCacheKey()); ?? see: COutputCache::getIsContentCached()

            $outputCache->getIsContentCached();
        }
    }
}